spring.application.name=ProjetoDiamante04

spring.datasource.url=jdbc:postgresql://localhost:5432/campusgigs
spring.datasource.username=campusgigs
spring.datasource.password=campusgigs

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=yF7U6goen44L4MnfQkC1u4zZHXwMwCbPBi0VB6KWEb0=
jwt.expiration=3600000
